spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daoyundb?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
  redis:
    port: 6379
    timeout: 50000
    password: 123456
aliyun:
  accessKeyID: LTAI5tSK1XcVyRECEJotx48k
  accessKeySecret: jDVzBYFEp43EuiUSUzghz4yADZKTyT
mybatis:
  type-aliases-package: com.zx.daoyundev.entity
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapping/*Mapper.xml
server:
  port: 8082

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

